### ISSUE TITLE
Override AclAuthorization - isAuthorized method

### ISSUE THREAD

**Issue by mwalper** [API-Skeletons/zf-oauth2-doctrine-permissions-acl#2]
Hi, i like to implement my own isAuthorized Method, preferably overloading the existing one by extending from
`ZF\OAuth2\Doctrine\Permissions\Acl\Authorization\AclAuthorization.` 
Maybe someone can explain me how to do it, because there seems no easy way to do that.
Thanks

**Comment by TomHAnderson** [comment]
Override and provide your own factory:

https://github.com/API-Skeletons/zf-oauth2-doctrine-permissions-acl/blob/master/src/ConfigProvider.php#L37
